# Started 12/27

In [1]:
import pygame
import random
import matplotlib.pyplot as plt
import math as ma
import numpy as np
import scipy as sp
from scipy.spatial.transform import Rotation as R

pygame 2.0.0 (SDL 2.0.12, python 3.7.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [8]:
def outAround2Vector(out, around):
    '''
    Takes 0,0,1 rotates it round the x axis (down) by the out angle and then rotates it around the z axis by the around angle
    only works with one pair of angles at the momen
    '''
    return R.from_euler('xz', [out, around],degrees=True).apply(np.array([0, 0, 1]))

In [18]:
outs=np.array([45,90,135])
arounds=np.array([0,45,90])
def outAround2Vector(out, around):
    '''
    Takes 0,0,1 rotates it round the x axis (down) by the out angle and then rotates it around the z axis by the around angle
    only works with one pair of angles at the momen
    '''
    Oa = np.array([out,around]).T
    print(Oa)
    return R.from_euler('xz', Oa,degrees=True).apply(np.array([0, 0, 1]))

In [19]:
outAround2Vector(45,90)

[45 90]


array([0.70710678, 0.        , 0.70710678])

In [20]:
outAround2Vector(outs,arounds)

[[ 45   0]
 [ 90  45]
 [135  90]]


array([[ 0.00000000e+00, -7.07106781e-01,  7.07106781e-01],
       [ 7.07106781e-01, -7.07106781e-01,  5.55111512e-17],
       [ 7.07106781e-01,  0.00000000e+00, -7.07106781e-01]])